export const MIGRATION_PROVIDERS = [
  {
    id: 'clio',
    name: 'Clio Manage',
    shortName: 'Clio',
    category: 'Legacy SaaS',
    migrationPath: 'CSV and API-ready',
    apiStatus: 'connector-planned',
    accent: '#2563eb',
    moat: 'Matter, contact, billing, and document history moved into an agentic workspace.',
    acceptedFormats: ['.csv', '.json', '.txt'],
    supportedEntities: ['clients', 'matters', 'tasks', 'notes', 'timeEntries', 'invoices', 'documents'],
    sampleHeaders: ['Matter Number', 'Matter Description', 'Client Name', 'Responsible Attorney', 'Open Date'],
  },
  {
    id: 'mycase',
    name: 'MyCase',
    shortName: 'MyCase',
    category: 'Legacy SaaS',
    migrationPath: 'CSV and API-ready',
    apiStatus: 'connector-planned',
    accent: '#0f766e',
    moat: 'Client portal records and firm contacts can land in CRM and knowledge base on day one.',
    acceptedFormats: ['.csv', '.json', '.txt'],
    supportedEntities: ['clients', 'matters', 'calendar', 'tasks', 'notes', 'timeEntries', 'invoices'],
    sampleHeaders: ['Case Name', 'Client', 'Contact Email', 'Phone', 'Status'],
  },
  {
    id: 'practicepanther',
    name: 'PracticePanther',
    shortName: 'PracticePanther',
    category: 'Legacy SaaS',
    migrationPath: 'CSV-first',
    apiStatus: 'export-supported',
    accent: '#f59e0b',
    moat: 'Panther exports become NemoC LAW AI matters, contacts, time entries, and searchable context.',
    acceptedFormats: ['.csv', '.json', '.txt'],
    supportedEntities: ['clients', 'matters', 'tasks', 'notes', 'timeEntries', 'expenses', 'invoices'],
    sampleHeaders: ['Account Name', 'Matter Name', 'Matter Status', 'Assigned To', 'Billable Hours'],
  },
  {
    id: 'smokeball',
    name: 'Smokeball',
    shortName: 'Smokeball',
    category: 'Legacy SaaS',
    migrationPath: 'CSV and document-ready',
    apiStatus: 'export-supported',
    accent: '#dc2626',
    moat: 'Document-heavy practices keep the file context while NemoC LAW AI adds automation and agent routing.',
    acceptedFormats: ['.csv', '.json', '.txt'],
    supportedEntities: ['clients', 'matters', 'tasks', 'notes', 'timeEntries', 'documents'],
    sampleHeaders: ['Matter', 'Client', 'Matter Type', 'Opened', 'Description'],
  },
  {
    id: 'cosmolex',
    name: 'CosmoLex',
    shortName: 'CosmoLex',
    category: 'Legacy SaaS',
    migrationPath: 'CSV-first',
    apiStatus: 'export-supported',
    accent: '#7c3aed',
    moat: 'Accounting and trust-account exports are preserved as auditable finance knowledge.',
    acceptedFormats: ['.csv', '.json', '.txt'],
    supportedEntities: ['clients', 'matters', 'timeEntries', 'expenses', 'invoices', 'trustBalances'],
    sampleHeaders: ['Client Matter', 'Trust Balance', 'Invoice Number', 'Expense Amount', 'Matter Status'],
  },
  {
    id: 'rocketmatter',
    name: 'Rocket Matter',
    shortName: 'Rocket Matter',
    category: 'Legacy SaaS',
    migrationPath: 'CSV-first',
    apiStatus: 'export-supported',
    accent: '#0891b2',
    moat: 'Matter, billing, and legacy task exports are staged for immediate NemoC LAW AI billing intelligence.',
    acceptedFormats: ['.csv', '.json', '.txt'],
    supportedEntities: ['clients', 'matters', 'tasks', 'notes', 'timeEntries', 'invoices'],
    sampleHeaders: ['Matter Name', 'Client Name', 'Activity', 'Hours', 'Rate'],
  },
  {
    id: 'lawcus',
    name: 'Lawcus',
    shortName: 'Lawcus',
    category: 'Modern SaaS',
    migrationPath: 'CSV and API-ready',
    apiStatus: 'connector-planned',
    accent: '#16a34a',
    moat: 'CRM pipeline data becomes actionable client intake and matter context for agents.',
    acceptedFormats: ['.csv', '.json', '.txt'],
    supportedEntities: ['clients', 'matters', 'tasks', 'notes', 'timeEntries'],
    sampleHeaders: ['Pipeline Stage', 'Lead Name', 'Client Email', 'Matter Name', 'Due Date'],
  },
  {
    id: 'caret',
    name: 'CARET Legal',
    shortName: 'CARET',
    category: 'Legacy SaaS',
    migrationPath: 'CSV-first',
    apiStatus: 'export-supported',
    accent: '#334155',
    moat: 'Practice records move into a lower-overhead workspace with agent-assisted execution.',
    acceptedFormats: ['.csv', '.json', '.txt'],
    supportedEntities: ['clients', 'matters', 'calendar', 'tasks', 'notes', 'timeEntries', 'documents'],
    sampleHeaders: ['Contact Name', 'Matter', 'Practice Area', 'Deadline', 'Notes'],
  },
  {
    id: 'actionstep',
    name: 'Actionstep',
    shortName: 'Actionstep',
    category: 'Workflow SaaS',
    migrationPath: 'CSV and API-ready',
    apiStatus: 'connector-planned',
    accent: '#9333ea',
    moat: 'Workflow-centric firms can keep matter stages while moving to an AI-native operating model.',
    acceptedFormats: ['.csv', '.json', '.txt'],
    supportedEntities: ['clients', 'matters', 'tasks', 'notes', 'timeEntries', 'documents', 'invoices'],
    sampleHeaders: ['Action Name', 'Step', 'Participant', 'Client', 'Assigned Lawyer'],
  },
  {
    id: 'filevine',
    name: 'Filevine',
    shortName: 'Filevine',
    category: 'Modern SaaS',
    migrationPath: 'CSV and API-ready',
    apiStatus: 'connector-planned',
    accent: '#2563eb',
    moat: 'High-volume case data can be staged into matters and searchable case knowledge.',
    acceptedFormats: ['.csv', '.json', '.txt'],
    supportedEntities: ['clients', 'matters', 'tasks', 'notes', 'timeEntries', 'documents'],
    sampleHeaders: ['Project Name', 'Client Full Name', 'Phase', 'Case Type', 'Last Activity'],
  },
];

export const MIGRATION_PROVIDER_IDS = MIGRATION_PROVIDERS.map(provider => provider.id);

export function getMigrationProvider(providerId) {
  return MIGRATION_PROVIDERS.find(provider => provider.id === providerId) || MIGRATION_PROVIDERS[0];
}
